### ISSUE TITLE
ThirdPersonCamera.gd:84 - Invalid get index 'spring_length' (on base: 'null instance').

### ISSUE THREAD

**Issue by GKaszewski** [JeanKouss/godot-third-person-camera#11]
Hi, I am getting 2 errors.

`res://addons/third-person-camera/third_person_camera/ThirdPersonCamera.gd:146 - Invalid set index 'keep_aspect' (on base: 'null instance') with value of type 'int'.
  res://addons/third-person-camera/third_person_camera/ThirdPersonCamera.gd:84 - Invalid get index 'spring_length' (on base: 'null instance').`
![image](https://github.com/JeanKouss/godot-third-person-camera/assets/42281413/df0f3983-616e-431f-9329-59c51f30710f)

**Comment by JeanKouss** [comment]
Hello!
Thank you for raising this issue. It appears to be related to `_camera` and `_camera_spring_arm` being `null`, but there is not enough information.
Please, provide the steps to reproduce it or a minimal reproduction project.

**Comment by GKaszewski** [comment]
I downloaded the zip from releases added addons to my project. Enabled it. Added ThirdPersonCamera as a child of my character and got errors. Interestingly when i opened demo projected everything worked so I have no idea.

**Comment by GKaszewski** [comment]
![image](https://github.com/JeanKouss/godot-third-person-camera/assets/42281413/70269997-4b89-4708-85c5-c78221f440ef)

**Comment by JeanKouss** [comment]
According to the picture, it seems like you added it as a simple node.
You should use the hole `ThirdPersonCamera.tscn` scene of the addon.

**Comment by GKaszewski** [comment]
Oh okay, thanks!
