### ISSUE TITLE
Add a preview button.

### ISSUE THREAD

**Issue by JeanKouss** [JeanKouss/godot-third-person-camera#13]
When a `Camera3D` is selected, a preview button is available to toggle the camera preview.
![image](https://github.com/JeanKouss/godot-third-person-camera/assets/70731505/d9083c06-853b-4727-94be-08629e08c075)

It could be nice to have this button for `ThirdPersonCamera` also.

**Comment by JeanKouss** [comment]
This could help.
https://ask.godotengine.org/6369/how-to-get-the-editors-camera

**Comment by JeanKouss** [comment]
I initially considered updating the editor camera every frame with the properties of the `ThirdPersonCamera` (position, rotation, fov, etc.). However, this approach presented challenges:

1. Difficulty in selecting and managing the editor camera.
2. Potential issues if the editor layout changes, requiring updates.

Instead, I suggest allowing users to add a `Camera3D` as a child to the `ThirdPersonCamera` scene. Once added, this `Camera3D` would be automatically configured as a preview camera. Users can then select this camera and toggle its preview mode.

An implementation of that solution is on the branch [preview_cam](https://github.com/JeanKouss/godot-third-person-camera/tree/preview_cam).

**How to try it?**
1. Open test project
2. Add a `Camera3D` node to `ThirdPersonCamera` scene. The camera should be automatically renamed.
3. Select the added camera and toggle its preview mode
4. Twerk `ThirdPersonCamera` properties: the preview should update

__Warning:__ That is not the final implementation

**Comment by JeanKouss** [comment]
This can seem to be a little weird. 

One can just display the children of `ThirdPersonCamera` scene and directly select the camera (the one of ThirdPersonCamera scene itself) instead of adding a new one.

But I thought encapsulating TPC nodes is a priority.

**Comment by eistre91** [comment]
There might be a way to use the RenderingServer API to do this while maintaining encapsulation. 

As I understand it, the Godot engine code itself uses this when it sets the preview camera: https://github.com/godotengine/godot/blob/da945ce6266ce27ba63b6b08dc0eb2414594f7cb/editor/plugins/node_3d_editor_plugin.cpp#L3699

Rendering Server Docs:
https://docs.godotengine.org/en/stable/classes/class_renderingserver.html#class-renderingserver

**Comment by JeanKouss** [comment]
Really interesting. They seem to use this method in the engine: https://docs.godotengine.org/en/stable/classes/class_renderingserver.html#class-renderingserver-method-viewport-attach-camera

I will give it a try.

**Comment by JeanKouss** [comment]
So I have tried it with a simple test implementation.
I added a boolean export variable and 2 functions: `_activate_preview` and `_desactivate_preview`.
```
##
@export var preview : bool = false :
	set(value) :
		preview = value
		_activate_preview() if preview else _desactivate_preview()

func _activate_preview() :
	var vp_rid = EditorInterface.get_editor_viewport_3d(0).get_viewport_rid()
	RenderingServer.viewport_attach_camera(vp_rid, get_camera())


func _desactivate_preview() :
	var vp_rid = EditorInterface.get_editor_viewport_3d(0).get_viewport_rid()
	var vp_camera = EditorInterface.get_editor_viewport_3d(0).get_camera_3d()
	RenderingServer.viewport_attach_camera(vp_rid, vp_camera)
```

But once I turn preview `true` in the inspector, I get a grey viewport.
![image](https://github.com/JeanKouss/godot-third-person-camera/assets/70731505/690d3db3-2784-434a-a7d0-f4aa39e5f4a0)

**Comment by eistre91** [comment]
That's unfortunate. Maybe there's some additional trick to it. I'll give it a try in the next few days and see if I can find something.

**Comment by eistre91** [comment]
This works to preview the camera. Added a variable to keep track of the camera prior to replacing with the preview camera. And then I think the main thing was passing in the Camera3D RID, rather than the Node itself.

```
##
@export var preview : bool = false :
	set(value) :
		preview = value
		_activate_preview() if preview else _deactivate_preview()

var _restore_prev_camera: Camera3D

func _activate_preview() :
	_restore_prev_camera = EditorInterface.get_editor_viewport_3d(0).get_camera_3d()

	var vp_rid = EditorInterface.get_editor_viewport_3d(0).get_viewport_rid()
	RenderingServer.viewport_attach_camera(vp_rid, get_camera().get_camera_rid())


func _deactivate_preview() :
	var vp_rid = EditorInterface.get_editor_viewport_3d(0).get_viewport_rid()
	RenderingServer.viewport_attach_camera(vp_rid, _restore_prev_camera.get_camera_rid())
```

**Comment by JeanKouss** [comment]
Thanks to your indications, I have started a new implementation on the branch [feature-preview_camera](https://github.com/JeanKouss/godot-third-person-camera/tree/feature-preview_camera).

I added a button on the viewport top bar so the user can choose the viewport they want to preview in.

It needs some testing and cleaning.

**Comment by JeanKouss** [comment]
Finaly https://github.com/ramokz/phantom-camera inspired implémentation was made.
