### ISSUE TITLE
Add option for mouse_follow to rotate around the y axis

### ISSUE THREAD

**Issue by nicholasrobertm** [JeanKouss/godot-third-person-camera#18]
Currently if you enable `mouse_follow` only the horizontal direction is tracked / followed. It'd be useful to have the option to track the vertical direction as well to allow it to be used as an action camera

**Comment by JeanKouss** [comment]
Actually `mouse_follow ` affect the camera on both horizontal and vertical direction.

[https://github.com/JeanKouss/godot-third-person-camera#mouse-follow](url)

![mouse_follow_demo](https://github.com/JeanKouss/godot-third-person-camera/assets/70731505/8ed1a893-31eb-41f7-a4e0-7de4099fa547)

Perhaps you set the Y sensibility very low.
