### ISSUE TITLE
Implement camera shake

### ISSUE THREAD

**Issue by JeanKouss** [JeanKouss/godot-third-person-camera#19]
Implement camera shake

**Comment by eistre91** [comment]
I'm going to want this in my current project so I'll attempt an implementation soon.

**Comment by eistre91** [comment]
I've put up a WIP PR for camera shake. A few oddities in there. 

https://github.com/JeanKouss/godot-third-person-camera/pull/25

**Comment by JeanKouss** [comment]
I made some enhancement proposition 

https://github.com/eistre91/godot-third-person-camera/pull/1
